<?php

return [
    'ranges' => [
        "2 DR Divan Pocket Set Deal",
        "24\" Flat Headboard",
        "26\" Flat Headboard",
        "6 x SOLACE 1000",
        "60\"Statement Headboard",
        "AMALFI",
        "Chesterfield Floorstanding Headboard",
        "Chesterfield Standard Headboard",
        "Cloud 4500",
        "Cloud 5000",
        "Cloud 5500",
        "Essential 26\" Strutted",
        "Essential 54\" Floorstanding H/B",
        "Essential Base on Legs",
        "Essential Bed Frame",
        "Essential Divan Base",
        "Essential Flat 20'' Headboard",
        "Essential Ottoman Base",
        "Essential Ottoman Bed Frame",
        "Essential Standard Base",
        "Floor Standing Headboard",
        "Floorstanding Headboard",
        "Gel Firmer 2000",
        "Gel Medium 1500",
        "Gel Softer 1000",
        "GENESIS",
        "Haven 26\" Strutted",
        "Haven 54\" Floorstanding H/B",
        "Haven Base on Legs",
        "Haven Bed Frame",
        "Haven Ottoman Base",
        "Haven Ottoman Bed Frame",
        "Haven Standard Base",
        "HERCULES",
        "Hyder Cloud Pocket 1000 Adjustable",
        "Hyder Elevate Pocket Gel 1000 Adjustable",
        "Hyder Soft Touch Pocket Memory 1000 Adjustable",
        "Hyder Wool Luxury Soft 3000",
        "KOBI",
        "LINEN",
        "LOOP",
        "Low Divan Base",
        "Luxury Firmer 2000",
        "Luxury Medium 1500",
        "Luxury Softer 1000",
        "Memory 1200 Comfort",
        "Memory Firmer 2000",
        "Memory Medium 1500",
        "Memory Softer 1000",
        "Natural Firmer 2000",
        "Natural Medium 1500",
        "Natural Softer 1000",
        "Ortho Firm Support",
        "Ortho Pocket Cashmere",
        "Ottoman Set Deal",
        "Ottoman Side Base",
        "Ottoman Twix Base",
        "PAOLO",
        "PLUSH VELVET",
        "Premium Divan Base",
        "Purity 11000",
        "Purity 11500",
        "Purity 12000",
        "Saffron Ortho 3D",
        "Savile Bed Company Chelsea 3000 Pillow Top",
        "Savile Bed Company Kensington 2000",
        "Savile Bed Company Mayfair 5000",
        "Savile Bed Frame",
        "Savile Luxury Base on Legs",
        "Savile Luxury Ottoman base",
        "Savile Luxury Pocket Sprung Base",
        "Savile Luxury Sprung Base",
        "Savile Luxury Standard Soilid Divan Base",
        "Savile Ottoman Bed Frame",
        "Serenity 5000",
        "Serenity 5500",
        "Serenity 6000",
        "Signature Divan Base",
        "Silk 1500 Comfort",
        "Solace 1000 Comfort",
        "SOULFUL",
        "Spring King Backcare Ultimate 3000",
        "Spring King Grand Ortho 2000",
        "Spring King Harmony Ortho Pocket",
        "Spring King Madrid 1000 Pocket",
        "Spring King Memory Ortho",
        "Spring King Pocket Backcare 1500",
        "Spring King Pocket Memory Ortho 1500",
        "Spring King Ruby Ortho Extra Firm",
        "Spring King Sanctuary Spa 2000 Pillow Top",
        "Spring King Tuscany 2000",
        "Spring King Wool Sublime 2000 Pillow Top",
        "Standard Headboard",
        "Sublime 1000",
        "Sublime 1500",
        "Sublime 2000",
        "Support Extra Firmer 2000",
        "Support Firm 1500",
        "VINTAGE VELVET",
        "WOOL"
    ],
    'section' => [
        "Bed Frame Models",
        "BEDS ONLINE",
        "CAT A FABRICS",
        "CAT B FABRICS",
        "Haven",
        "Headboard Design",
        "Hyders Essential",
        "Savile",
    ],
    'type' => [
        "Base",
        "Bed Frame",
        "Bed Frame Design",
        "Divan Base",
        "Fabric",
        "Headboard",
        "Headboard Design",
        "Mattress",
        "Mattress H/S/S",
        "Mattress+HB+Base",
        "Ottoman",
    ]
];